const FULL_FIELD = 'FULL_FIELD';
const ADD_VALUE = 'ADD_VALUE';
const CHANGE_VALUE = 'CHANGE_VALUE';
const EXP_FIELD = 'EXP_FIELD';
const CHANGE_COMP = 'CHANGE_COMP';
const NEW_VALUE = 'NEW_VALUE';
const START_POS = 'START_POS';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
const MOVE_UP = 'MOVE_UP';
const MOVE_DOWN = 'MOVE_DOWN';
const MOVE_RIGHT = 'MOVE_RIGHT';
const MOVE_LEFT = 'MOVE_LEFT';
const SAVE_EXP = 'SAVE_EXP';
const NEW_EXP = 'NEW_EXP';
export {
  FULL_FIELD,
  ADD_VALUE,
  CHANGE_VALUE,
  EXP_FIELD,
  CHANGE_COMP,
  NEW_VALUE,
  START_POS,
  AUTH_SUCCESS,
  AUTH_LOGOUT,
  MOVE_UP,
  MOVE_DOWN,
  MOVE_RIGHT,
  MOVE_LEFT,
  SAVE_EXP,
    NEW_EXP
};
