const FULL_FIELD = 'FULL_FIELD';
const ADD_VALUE = 'ADD_VALUE';
const CHANGE_VALUE = 'CHANGE_VALUE';
const EXP_FIELD = 'EXP_FIELD';
// <<<<<<< HEAD
const CHANGE_COMP = 'CHANGE_COMP';
const NEW_VALUE = 'NEW_VALUE';
const START_POS = 'START_POS';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
export {FULL_FIELD, ADD_VALUE, CHANGE_VALUE, EXP_FIELD, CHANGE_COMP, NEW_VALUE, START_POS, AUTH_SUCCESS, AUTH_LOGOUT}
// =======
// const AUTH_SUCCESS = 'AUTH_SUCCESS';
// const AUTH_LOGOUT = 'AUTH_LOGOUT';
//
// export {FULL_FIELD, ADD_VALUE, CHANGE_VALUE, EXP_FIELD, AUTH_SUCCESS, AUTH_LOGOUT};
// >>>>>>> d8cc8ea847f544145383d3c2bac0b8a90340087c
