const FULL_FIELD = 'FULL_FIELD';
const ADD_VALUE = 'ADD_VALUE';
const CHANGE_VALUE = 'CHANGE_VALUE';
const EXP_FIELD = 'EXP_FIELD';
const CHANGE_COMP = 'CHANGE_COMP';
const NEW_VALUE = 'NEW_VALUE';
const START_POS = 'START_POS';
export {FULL_FIELD, ADD_VALUE, CHANGE_VALUE, EXP_FIELD, CHANGE_COMP, NEW_VALUE, START_POS}
