const mongoose = require('mongoose');
const {Field} = require('./field');

mongoose.connect('mongodb+srv://admin:LnCC67f8@labirynth-420rj.mongodb.net',
    {useNewUrlParser: true}).then(() => {
  Field.insertMany(
    {line: [
          {
            line: [
              {index: 'a1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p1', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p2', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p3', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p4', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p5', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p6', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p7', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p8', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p9', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p10', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
          {
            line: [
              {index: 'a11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'b11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'c11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'd11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'e11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'f11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'g11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'h11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'i11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'j11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'k11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'l11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'm11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'n11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'o11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
              {index: 'p11', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
          },
        {
          line: [
            {index: 'a12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'b12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'c12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'd12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'e12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'f12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'g12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'h12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'i12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'j12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'k12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'l12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'm12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'n12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'o12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'p12', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
        },
        {
          line: [
            {index: 'a13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'b13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'c13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'd13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'e13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'f13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'g13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'h13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'i13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'j13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'k13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'l13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'm13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'n13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'o13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'p13', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
        },
        {
          line: [
            {index: 'a14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'b14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'c14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'd14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'e14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'f14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'g14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'h14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'i14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'j14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'k14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'l14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'm14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'n14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'o14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'p14', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
        },
        {
          line: [
            {index: 'a15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'b15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'c15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'd15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'e15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'f15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'g15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'h15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'i15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'j15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'k15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'l15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'm15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'n15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'o15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'p15', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
        },
        {
          line: [
            {index: 'a16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'b16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'c16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'd16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'e16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'f16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'g16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'h16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'i16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'j16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'k16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'l16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'm16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'n16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'o16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false},
            {index: 'p16', wall: false, food: false, fakeFood: false, entry: false, exit: false, pedal: false, lamp: false, sound: false, value: null, start: false}],
        },
        ]}
      );
});
