const mongoose = require('mongoose');
const {Field} = require('./field');

mongoose.connect('mongodb+srv://admin:LnCC67f8@labirynth-420rj.mongodb.net',
    {useNewUrlParser: true}).then(() => {
  Field.insertMany(
    {line: [
          {
            line: [
              {index: 'a1', wall: false, food: false, start: false, value: null},
              {index: 'b1', wall: false, food: false, start: false, value: null},
              {index: 'c1', wall: false, food: false, start: false, value: null},
              {index: 'd1', wall: false, food: false, start: false, value: null},
              {index: 'e1', wall: false, food: false, start: false, value: null},
              {index: 'f1', wall: false, food: false, start: false, value: null},
              {index: 'g1', wall: false, food: false, start: false, value: null},
              {index: 'h1', wall: false, food: false, start: false, value: null},
              {index: 'i1', wall: false, food: false, start: false, value: null},
              {index: 'j1', wall: false, food: false, start: false, value: null},
              {index: 'k1', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a2', wall: false, food: false, start: false, value: null},
              {index: 'b2', wall: false, food: false, start: false, value: null},
              {index: 'c2', wall: false, food: false, start: false, value: null},
              {index: 'd2', wall: false, food: false, start: false, value: null},
              {index: 'e2', wall: false, food: false, start: false, value: null},
              {index: 'f2', wall: false, food: false, start: false, value: null},
              {index: 'g2', wall: false, food: false, start: false, value: null},
              {index: 'h2', wall: false, food: false, start: false, value: null},
              {index: 'i2', wall: false, food: false, start: false, value: null},
              {index: 'j2', wall: false, food: false, start: false, value: null},
              {index: 'k2', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a3', wall: false, food: false, start: false, value: null},
              {index: 'b3', wall: false, food: false, start: false, value: null},
              {index: 'c3', wall: false, food: false, start: false, value: null},
              {index: 'd3', wall: false, food: false, start: false, value: null},
              {index: 'e3', wall: false, food: false, start: false, value: null},
              {index: 'f3', wall: false, food: false, start: false, value: null},
              {index: 'g3', wall: false, food: false, start: false, value: null},
              {index: 'h3', wall: false, food: false, start: false, value: null},
              {index: 'i3', wall: false, food: false, start: false, value: null},
              {index: 'j3', wall: false, food: false, start: false, value: null},
              {index: 'k3', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a4', wall: false, food: false, start: false, value: null},
              {index: 'b4', wall: false, food: false, start: false, value: null},
              {index: 'c4', wall: false, food: false, start: false, value: null},
              {index: 'd4', wall: false, food: false, start: false, value: null},
              {index: 'e4', wall: false, food: false, start: false, value: null},
              {index: 'f4', wall: false, food: false, start: false, value: null},
              {index: 'g4', wall: false, food: false, start: false, value: null},
              {index: 'h4', wall: false, food: false, start: false, value: null},
              {index: 'i4', wall: false, food: false, start: false, value: null},
              {index: 'j4', wall: false, food: false, start: false, value: null},
              {index: 'k4', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a5', wall: false, food: false, start: false, value: null},
              {index: 'b5', wall: false, food: false, start: false, value: null},
              {index: 'c5', wall: false, food: false, start: false, value: null},
              {index: 'd5', wall: false, food: false, start: false, value: null},
              {index: 'e5', wall: false, food: false, start: false, value: null},
              {index: 'f5', wall: false, food: false, start: false, value: null},
              {index: 'g5', wall: false, food: false, start: false, value: null},
              {index: 'h5', wall: false, food: false, start: false, value: null},
              {index: 'i5', wall: false, food: false, start: false, value: null},
              {index: 'j5', wall: false, food: false, start: false, value: null},
              {index: 'k5', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a6', wall: false, food: false, start: false, value: null},
              {index: 'b6', wall: false, food: false, start: false, value: null},
              {index: 'c6', wall: false, food: false, start: false, value: null},
              {index: 'd6', wall: false, food: false, start: false, value: null},
              {index: 'e6', wall: false, food: false, start: false, value: null},
              {index: 'f6', wall: false, food: false, start: false, value: null},
              {index: 'g6', wall: false, food: false, start: false, value: null},
              {index: 'h6', wall: false, food: false, start: false, value: null},
              {index: 'i6', wall: false, food: false, start: false, value: null},
              {index: 'j6', wall: false, food: false, start: false, value: null},
              {index: 'k6', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a7', wall: false, food: false, start: false, value: null},
              {index: 'b7', wall: false, food: false, start: false, value: null},
              {index: 'c7', wall: false, food: false, start: false, value: null},
              {index: 'd7', wall: false, food: false, start: false, value: null},
              {index: 'e7', wall: false, food: false, start: false, value: null},
              {index: 'f7', wall: false, food: false, start: false, value: null},
              {index: 'g7', wall: false, food: false, start: false, value: null},
              {index: 'h7', wall: false, food: false, start: false, value: null},
              {index: 'i7', wall: false, food: false, start: false, value: null},
              {index: 'j7', wall: false, food: false, start: false, value: null},
              {index: 'k7', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a8', wall: false, food: false, start: false, value: null},
              {index: 'b8', wall: false, food: false, start: false, value: null},
              {index: 'c8', wall: false, food: false, start: false, value: null},
              {index: 'd8', wall: false, food: false, start: false, value: null},
              {index: 'e8', wall: false, food: false, start: false, value: null},
              {index: 'f8', wall: false, food: false, start: false, value: null},
              {index: 'g8', wall: false, food: false, start: false, value: null},
              {index: 'h8', wall: false, food: false, start: false, value: null},
              {index: 'i8', wall: false, food: false, start: false, value: null},
              {index: 'j8', wall: false, food: false, start: false, value: null},
              {index: 'k8', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a9', wall: false, food: false, start: false, value: null},
              {index: 'b9', wall: false, food: false, start: false, value: null},
              {index: 'c9', wall: false, food: false, start: false, value: null},
              {index: 'd9', wall: false, food: false, start: false, value: null},
              {index: 'e9', wall: false, food: false, start: false, value: null},
              {index: 'f9', wall: false, food: false, start: false, value: null},
              {index: 'g9', wall: false, food: false, start: false, value: null},
              {index: 'h9', wall: false, food: false, start: false, value: null},
              {index: 'i9', wall: false, food: false, start: false, value: null},
              {index: 'j9', wall: false, food: false, start: false, value: null},
              {index: 'k9', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a10', wall: false, food: false, start: false, value: null},
              {index: 'b10', wall: false, food: false, start: false, value: null},
              {index: 'c10', wall: false, food: false, start: false, value: null},
              {index: 'd10', wall: false, food: false, start: false, value: null},
              {index: 'e10', wall: false, food: false, start: false, value: null},
              {index: 'f10', wall: false, food: false, start: false, value: null},
              {index: 'g10', wall: false, food: false, start: false, value: null},
              {index: 'h10', wall: false, food: false, start: false, value: null},
              {index: 'i10', wall: false, food: false, start: false, value: null},
              {index: 'j10', wall: false, food: false, start: false, value: null},
              {index: 'k10', wall: false, food: false, start: false, value: null}],
          },
          {
            line: [
              {index: 'a11', wall: false, food: false, start: false, value: null},
              {index: 'b11', wall: false, food: false, start: false, value: null},
              {index: 'c11', wall: false, food: false, start: false, value: null},
              {index: 'd11', wall: false, food: false, start: false, value: null},
              {index: 'e11', wall: false, food: false, start: false, value: null},
              {index: 'f11', wall: false, food: false, start: false, value: null},
              {index: 'g11', wall: false, food: false, start: false, value: null},
              {index: 'h11', wall: false, food: false, start: false, value: null},
              {index: 'i11', wall: false, food: false, start: false, value: null},
              {index: 'j11', wall: false, food: false, start: false, value: null},
              {index: 'k11', wall: false, food: false, start: false, value: null}],
          },
        ]}
      );
});
